---
output: 
  github_document:
    toc: true
    toc_depth: 2
    number_sections: true
fontsize: 11pt         # This is ignored for markdown, but left for completeness
geometry: margin=1in   # Also ignored in markdown
---


Create a flow diagram with clear arrows and boxes from the following components. Include the step-by-step copy used in the diagram as separate text below the final diagram in clear steps. Set 'Comfortaa' as the default font in the workspace for all text copy, flow diagams, and generated images. For the summary, use a voice and tone of an informative product designer that is highlighting the steps and pathways of the flow diagram in an practical and concise manner. 

Be succinct, 10-15 words per bullet point. 

when summarising the steps and creating the flow diagram, ignore specific variable related instructions e.g. set variable, set data, extract numbers, etc. Instead, stay high level and keep the summary and flow focused on describing the main steps without jargon or file related info. Consolidate and repetitive and high level intructions. 

Add a Tasks heading with three concise and appealing tasks this workflow can perform (bullet points). Then add a Benefits heading with three concise bullet points of the benefits to someone buying this product but pitched to improve their business and operations e.g. increase revenue, improve customer experience, etc.    

Redo the title I supply with a punchier title 

\  

## `r list.files(here::here("_template_init", "n8n"), pattern = "\\.txt$", full.names = F) |> stringr::str_remove_all(".txt")`


```{r, echo=F, eval=T, error=F, warning=F, message=F, results='none'}
library(readr)
library(jsonify)
library(htmltools)
library(here)

# get file
txt_path <- list.files(here("_template_init", "n8n"), pattern = "\\.txt$", full.names = TRUE)[1]

# read data
json_text <- read_lines(txt_path) |>
  paste(collapse = "\n") |>
  jsonify::from_json() |>         
  jsonify::to_json() |>           
  jsonify::pretty_json()          

# html output
html_output <- tags$pre(tags$code(json_text, style = "white-space: pre-wrap;"))
knitr::asis_output(as.character(html_output))


```
 
\  



